// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb1XxAUvta05xkTpvyE9fJ0dH3mcKmaLY',
    appId: '1:607610620583:web:faf266ab2336264d902982',
    messagingSenderId: '607610620583',
    projectId: 'lizx-3093e',
    authDomain: 'lizx-3093e.firebaseapp.com',
    storageBucket: 'lizx-3093e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPn6R4G5I9WJkRqGy-Yk0fn9LM3kABgBA',
    appId: '1:607610620583:android:13c771398b914154902982',
    messagingSenderId: '607610620583',
    projectId: 'lizx-3093e',
    storageBucket: 'lizx-3093e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnA1Ah_5UrWKaGTgXGZhA60tPRDRjWVAo',
    appId: '1:607610620583:ios:e113368a004100b9902982',
    messagingSenderId: '607610620583',
    projectId: 'lizx-3093e',
    storageBucket: 'lizx-3093e.firebasestorage.app',
    iosBundleId: 'com.example.lix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnA1Ah_5UrWKaGTgXGZhA60tPRDRjWVAo',
    appId: '1:607610620583:ios:e113368a004100b9902982',
    messagingSenderId: '607610620583',
    projectId: 'lizx-3093e',
    storageBucket: 'lizx-3093e.firebasestorage.app',
    iosBundleId: 'com.example.lix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb1XxAUvta05xkTpvyE9fJ0dH3mcKmaLY',
    appId: '1:607610620583:web:5303d753323d6642902982',
    messagingSenderId: '607610620583',
    projectId: 'lizx-3093e',
    authDomain: 'lizx-3093e.firebaseapp.com',
    storageBucket: 'lizx-3093e.firebasestorage.app',
  );
}
