import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static const _key = 'selectedLanguage';
  static final LanguageService _instance = LanguageService._();
  factory LanguageService() => _instance;
  LanguageService._();

  String _language = 'English';
  Locale _locale = const Locale('en');

  String get language => _language;
  Locale get locale => _locale;

  // ── Language → Locale map ─────────────────────────────
  static const Map<String, Locale> _localeMap = {
    'Hindi': Locale('hi'),
    'Tamil': Locale('ta'),
    'Telugu': Locale('te'),
    'Kannada': Locale('kn'),
    'Malayalam': Locale('ml'),
    'Bengali': Locale('bn'),
    'Marathi': Locale('mr'),
    'Gujarati': Locale('gu'),
    'Punjabi': Locale('pa'),
    'Odia': Locale('or'),
    'Urdu': Locale('ur'),
    'Assamese': Locale('as'),
    'Kashmiri': Locale('ks'),
    'Konkani': Locale('kok'),
    'Maithili': Locale('mai'),
    'Manipuri': Locale('mni'),
    'Nepali': Locale('ne'),
    'Sanskrit': Locale('sa'),
    'Santali': Locale('sat'),
    'Sindhi': Locale('sd'),
    'Bodo': Locale('brx'),
    'Dogri': Locale('doi'),
    'English': Locale('en'),
    'Mandarin': Locale('zh'),
    'Spanish': Locale('es'),
    'French': Locale('fr'),
    'Arabic': Locale('ar'),
    'Portuguese': Locale('pt'),
    'Russian': Locale('ru'),
    'Japanese': Locale('ja'),
    'German': Locale('de'),
    'Korean': Locale('ko'),
    'Italian': Locale('it'),
    'Turkish': Locale('tr'),
    'Dutch': Locale('nl'),
    'Polish': Locale('pl'),
    'Swedish': Locale('sv'),
    'Greek': Locale('el'),
    'Hebrew': Locale('he'),
    'Thai': Locale('th'),
    'Vietnamese': Locale('vi'),
    'Indonesian': Locale('id'),
  };

  static const _rtlLanguages = {
    'Arabic',
    'Urdu',
    'Hebrew',
    'Sindhi',
    'Kashmiri',
  };

  bool get isRTL => _rtlLanguages.contains(_language);

  static List<Locale> get supportedLocales =>
      _localeMap.values.toSet().toList();

  // ── Full translation map — all 42 languages ───────────
  static final Map<String, Map<String, String>> _translations = {
    'English': {
      'History': 'History',
      'Favourites': 'Favourites',
      'Login': 'Login',
      'Logout': 'Logout',
      'Language': 'Language',
      'Dark Mode': 'Dark Mode',
      'Help & Support': 'Help & Support',
      'About Lix': 'About Lix',
      'Selected': 'Selected',
      'No language found': 'No language found',
      'Search language...': 'Search language...',
      'Search': 'Search',
      'Indian': 'Indian',
      'Foreign': 'Foreign',
      'Your Top Moods': 'Your Top Moods',
      'Settings': 'Settings',
      'Contact Us': 'Contact Us',
      'FAQs': 'FAQs',
      'Version': 'Version',
      'Build Number': 'Build Number',
      'Release Year': 'Release Year',
      'Platform': 'Platform',
      'Data Source': 'Data Source',
      'Backend': 'Backend',
      'Legal': 'Legal',
      'Privacy Policy': 'Privacy Policy',
      'Terms of Service': 'Terms of Service',
      'Contact': 'Contact',
      'Acknowledgements': 'Acknowledgements',
      'Notifications': 'Notifications',
      'Profile': 'Profile',
      'Movies': 'Movies',
      'Music': 'Music',
      'Chat': 'Chat',
      'Happy': 'Happy',
      'Sad': 'Sad',
      'Anxious': 'Anxious',
      'Bored': 'Bored',
      'Motivated': 'Motivated',
      'Romantic': 'Romantic',
    },

    'Hindi': {
      'History': 'इतिहास',
      'Favourites': 'पसंदीदा',
      'Login': 'लॉगिन',
      'Logout': 'लॉगआउट',
      'Language': 'भाषा',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'सहायता',
      'About Lix': 'लिक्स के बारे में',
      'Selected': 'चुना गया',
      'No language found': 'कोई भाषा नहीं मिली',
      'Search language...': 'भाषा खोजें...',
      'Search': 'खोज',
      'Indian': 'भारतीय',
      'Foreign': 'विदेशी',
      'Your Top Moods': 'आपके टॉप मूड',
      'Settings': 'सेटिंग्स',
      'Contact Us': 'संपर्क करें',
      'FAQs': 'सामान्य प्रश्न',
      'Version': 'संस्करण',
      'Build Number': 'बिल्ड संख्या',
      'Release Year': 'मुक्ति वर्ष',
      'Platform': 'प्लेटफ़ॉर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'बैकएंड',
      'Legal': 'कानूनी',
      'Privacy Policy': 'गोपनीयता नीति',
      'Terms of Service': 'सेवा नियम',
      'Contact': 'संपर्क',
      'Acknowledgements': 'समर्पण',
      'Notifications': 'सूचनाएं',
      'Profile': 'प्रोफ़ाइल',
      'Movies': 'फ़िल्में',
      'Music': 'संगीत',
      'Chat': 'चैट',
      'Happy': 'खुश',
      'Sad': 'उदास',
      'Anxious': 'चिंतित',
      'Bored': 'ऊब गया',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमांटिक',
    },

    'Tamil': {
      'History': 'வரலாறு',
      'Favourites': 'பிடித்தவை',
      'Login': 'உள்நுழைதல்',
      'Logout': 'வெளியேறு',
      'Language': 'மொழி',
      'Dark Mode': 'டார்க் மோட்',
      'Help & Support': 'உதவி',
      'About Lix': 'எலிஸ் பற்றி',
      'Selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'No language found': 'எந்த மொழியும் கிடைக்கவில்லை',
      'Search language...': 'மொழி தேடு...',
      'Search': 'தேடுக',
      'Indian': 'இந்திய',
      'Foreign': 'வெளிநாட்டு',
      'Your Top Moods': 'உங்கள் டாப் மூட்',
      'Settings': 'அமைப்புகள்',
      'Contact Us': 'எங்களை தொடர்பு கொள்ளவும்',
      'FAQs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'Version': 'பதிப்பு',
      'Build Number': 'பில்ட் எண்',
      'Release Year': 'ஆண்டு',
      'Platform': 'தளம்',
      'Data Source': 'தரவு மூலம்',
      'Backend': 'பின்புறம்',
      'Legal': 'சட்டரீதியான',
      'Privacy Policy': 'தனியுரிமை கொள்கை',
      'Terms of Service': 'சேவை விதிகள்',
      'Contact': 'தொடர்பு',
      'Acknowledgements': 'அங்கீகாரங்கள்',
      'Notifications': 'அறிவிப்புகள்',
      'Profile': 'சுயவிவரம்',
      'Movies': 'திரைப்படங்கள்',
      'Music': 'இசை',
      'Chat': 'அரட்டை',
      'Happy': 'மகிழ்ச்சி',
      'Sad': 'சோகம்',
      'Anxious': 'கவலை',
      'Bored': 'சலிப்பு',
      'Motivated': 'உந்துதல்',
      'Romantic': 'காதல்',
    },

    'Telugu': {
      'History': 'చరిత్ర',
      'Favourites': 'ప్రియమైనవి',
      'Login': 'లాగిన్ చేయండి',
      'Logout': 'లాగ్అవుట్ చేయండి',
      'Language': 'భాష',
      'Dark Mode': 'డార్క్ మోడ్',
      'Help & Support': 'సహాయం',
      'About Lix': 'Lix గురించి',
      'Selected': 'ఎంచుకోబడింది',
      'No language found': 'భాష కనుగొనబడలేదు',
      'Search language...': 'భాష శోధించండి...',
      'Search': 'శోధన',
      'Indian': 'భారతీయ',
      'Foreign': 'విదేశీ',
      'Your Top Moods': 'మీ టాప్ మూడ్స్',
      'Settings': 'సెట్టింగ్స్',
      'Contact Us': 'మమ్మల్ని సంప్రదించండి',
      'FAQs': 'సాధారణ ప్రశ్నలు',
      'Version': 'వెర్షన్',
      'Build Number': 'బిల్డ్ నంబర్',
      'Release Year': 'విడుదల సంవత్సరం',
      'Platform': 'ప్లాట్ఫామ్',
      'Data Source': 'డేటా సోర్స్',
      'Backend': 'బ్యాకెండ్',
      'Legal': 'న్యాయపరమైన',
      'Privacy Policy': 'గోప్యతా విధానం',
      'Terms of Service': 'సేవ నిబంధనలు',
      'Contact': 'సంప్రదించండి',
      'Acknowledgements': 'కృతజ్ఞతలు',
      'Notifications': 'నోటిఫికేషన్లు',
      'Profile': 'ప్రొఫైల్',
      'Movies': 'సినిమాలు',
      'Music': 'సంగీతం',
      'Chat': 'చాట్',
      'Happy': 'సంతోషం',
      'Sad': 'విచారం',
      'Anxious': 'ఆందోళన',
      'Bored': 'విసుగు',
      'Motivated': 'ప్రేరణ',
      'Romantic': 'రొమాంటిక్',
    },

    'Kannada': {
      'History': 'ಇತಿಹಾಸ',
      'Favourites': 'ನೆಚ್ಚಿನ',
      'Login': 'ಲಾಗಿನ್',
      'Logout': 'ಲಾಗ್ ಔಟ್',
      'Language': 'ಭಾಷೆ',
      'Dark Mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'Help & Support': 'ಸಹಾಯ',
      'About Lix': 'Lix ಬಗ್ಗೆ',
      'Selected': 'ಆಯ್ದ',
      'No language found': 'ಭಾಷೆ ಕಂಡುಬಂದಿಲ್ಲ',
      'Search language...': 'ಭಾಷೆ ಹುಡುಕಿ...',
      'Search': 'ಹುಡುಕಿ',
      'Indian': 'ಭಾರತೀಯ',
      'Foreign': 'ವಿದೇಶಿ',
      'Your Top Moods': 'ನಿಮ್ಮ ಟಾಪ್ ಮೂಡ್ಸ್',
      'Settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'Contact Us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿರಿ',
      'FAQs': 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
      'Version': 'ಆವೃತ್ತಿ',
      'Build Number': 'ಬಿಲ್ಡ್ ಸಂಖ್ಯೆ',
      'Release Year': 'ಬಿಡುಗಡೆ ವರ್ಷ',
      'Platform': 'ಪ್ಲಾಟ್ಫಾರ್ಮ್',
      'Data Source': 'ಡೇಟಾ ಮೂಲ',
      'Backend': 'ಬ್ಯಾಕ್ ಎಂಡ್',
      'Legal': 'ಕಾನೂನು',
      'Privacy Policy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'Terms of Service': 'ಸೇವೆಯ ನಿಯಮಗಳು',
      'Contact': 'ಸಂಪರ್ಕ',
      'Acknowledgements': 'ಸ್ವೀಕಾರ',
      'Notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'Profile': 'ಪ್ರೊಫೈಲ್',
      'Movies': 'ಚಲನಚಿತ್ರಗಳು',
      'Music': 'ಸಂಗೀತ',
      'Chat': 'ಚಾಟ್',
      'Happy': 'ಸಂತೋಷ',
      'Sad': 'ದುಃಖ',
      'Anxious': 'ಆತಂಕ',
      'Bored': 'ಬೇಸರ',
      'Motivated': 'ಪ್ರೇರಿತ',
      'Romantic': 'ರೊಮ್ಯಾಂಟಿಕ್',
    },

    'Malayalam': {
      'History': 'ചരിത്രം',
      'Favourites': 'പ്രിയപ്പെട്ടവ',
      'Login': 'ലോഗിൻ',
      'Logout': 'ലോഗ് ഔട്ട്',
      'Language': 'ഭാഷ',
      'Dark Mode': 'ഡാർക് മോഡ്',
      'Help & Support': 'സഹായം',
      'About Lix': 'Lix എന്താണ്',
      'Selected': 'തിരഞ്ഞെടുത്തത്',
      'No language found': 'ഭാഷ കണ്ടെത്തിയില്ല',
      'Search language...': 'ഭാഷ തിരയുക...',
      'Search': 'തിരയൽ',
      'Indian': 'ഇന്ത്യൻ',
      'Foreign': 'വിദേശി',
      'Your Top Moods': 'നിങ്ങളുടെ ടോപ്പ് മൂഡുകൾ',
      'Settings': 'സജ്ജീകരണങ്ങൾ',
      'Contact Us': 'ഞങ്ങളെ ബന്ധപ്പെടുക',
      'FAQs': 'സാധാരണ ചോദ്യങ്ങൾ',
      'Version': 'പതിപ്പ്',
      'Build Number': 'ബിൽഡ് നമ്പർ',
      'Release Year': 'പുറപ്പെടുവിക്കൽ വർഷം',
      'Platform': 'പ്ലാറ്റ്ഫോം',
      'Data Source': 'ഡാറ്റാ സോഴ്സ്',
      'Backend': 'ബാക്കെൻഡ്',
      'Legal': 'നിയമപരം',
      'Privacy Policy': 'സ്വകാര്യതാ നയം',
      'Terms of Service': 'സേവന നിബന്ധനകൾ',
      'Contact': 'ബന്ധപ്പെടുക',
      'Acknowledgements': 'പ്രശംസ',
      'Notifications': 'അറിയിപ്പുകൾ',
      'Profile': 'പ്രൊഫൈൽ',
      'Movies': 'സിനിമകൾ',
      'Music': 'സംഗീതം',
      'Chat': 'ചാറ്റ്',
      'Happy': 'സന്തോഷം',
      'Sad': 'സങ്കടം',
      'Anxious': 'ഉത്കണ്ഠ',
      'Bored': 'മടുപ്പ്',
      'Motivated': 'പ്രചോദിതൻ',
      'Romantic': 'റൊമാന്റിക്',
    },

    'Bengali': {
      'History': 'ইতিহাস',
      'Favourites': 'পছন্দের',
      'Login': 'লগ ইন',
      'Logout': 'লগ আউট',
      'Language': 'ভাষা',
      'Dark Mode': 'ডার্ক মোড',
      'Help & Support': 'সাহায্য',
      'About Lix': 'Lix সম্পর্কে',
      'Selected': 'নির্বাচিত',
      'No language found': 'ভাষা পাওয়া যায়নি',
      'Search language...': 'ভাষা খুঁজুন...',
      'Search': 'অনুসন্ধান',
      'Indian': 'ভারতীয়',
      'Foreign': 'বিদেশী',
      'Your Top Moods': 'আপনার শীর্ষ মেজাজ',
      'Settings': 'সেটিংস',
      'Contact Us': 'আমাদের সাথে যোগাযোগ করুন',
      'FAQs': 'সাধারণ প্রশ্নাবলী',
      'Version': 'সংস্করণ',
      'Build Number': 'বিল্ড নম্বর',
      'Release Year': 'মুক্তির বছর',
      'Platform': 'প্ল্যাটফর্ম',
      'Data Source': 'ডেটা উৎস',
      'Backend': 'ব্যাকএন্ড',
      'Legal': 'আইনি',
      'Privacy Policy': 'গোপনীয়তা নীতি',
      'Terms of Service': 'সেবার শর্তাবলী',
      'Contact': 'যোগাযোগ',
      'Acknowledgements': 'স্বীকৃতি',
      'Notifications': 'বিজ্ঞপ্তি',
      'Profile': 'প্রোফাইল',
      'Movies': 'সিনেমা',
      'Music': 'সংগীত',
      'Chat': 'চ্যাট',
      'Happy': 'খুশি',
      'Sad': 'দুঃখী',
      'Anxious': 'উদ্বিগ্ন',
      'Bored': 'বিরক্ত',
      'Motivated': 'অনুপ্রাণিত',
      'Romantic': 'রোমান্টিক',
    },

    'Marathi': {
      'History': 'इतिहास',
      'Favourites': 'आवडते',
      'Login': 'लॉगिन',
      'Logout': 'लॉगआउट',
      'Language': 'भाषा',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'मदत',
      'About Lix': 'Lix बद्दल',
      'Selected': 'निवडलेले',
      'No language found': 'भाषा सापडली नाही',
      'Search language...': 'भाषा शोधा...',
      'Search': 'शोध',
      'Indian': 'भारतीय',
      'Foreign': 'परदेशी',
      'Your Top Moods': 'तुमचे टॉप मूड्स',
      'Settings': 'सेटिंग्ज',
      'Contact Us': 'आमच्याशी संपर्क साधा',
      'FAQs': 'वारंवार विचारले जाणारे प्रश्न',
      'Version': 'आवृत्ती',
      'Build Number': 'बिल्ड क्रमांक',
      'Release Year': 'प्रकाशन वर्ष',
      'Platform': 'प्लॅटफॉर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'बॅकएंड',
      'Legal': 'कायदेशीर',
      'Privacy Policy': 'गोपनीयता धोरण',
      'Terms of Service': 'सेवेच्या अटी',
      'Contact': 'संपर्क',
      'Acknowledgements': 'आभार',
      'Notifications': 'सूचना',
      'Profile': 'प्रोफाइल',
      'Movies': 'चित्रपट',
      'Music': 'संगीत',
      'Chat': 'चॅट',
      'Happy': 'आनंदी',
      'Sad': 'दुःखी',
      'Anxious': 'काळजीत',
      'Bored': 'कंटाळलेला',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमँटिक',
    },

    'Gujarati': {
      'History': 'ઇતિહાસ',
      'Favourites': 'પ્રિય',
      'Login': 'લૉગ ઇન',
      'Logout': 'લૉગ આઉટ',
      'Language': 'ભાષા',
      'Dark Mode': 'ડાર્ક મોડ',
      'Help & Support': 'મદદ',
      'About Lix': 'Lix વિશે',
      'Selected': 'પસંદ કરેલ',
      'No language found': 'ભાષા મળી નથી',
      'Search language...': 'ભાષા શોધો...',
      'Search': 'શોધ',
      'Indian': 'ભારતીય',
      'Foreign': 'વિદેશી',
      'Your Top Moods': 'તમારા ટોપ મૂડ',
      'Settings': 'સેટિંગ્સ',
      'Contact Us': 'અમારો સંપર્ક કરો',
      'FAQs': 'વારંવાર પૂછાતા પ્રશ્નો',
      'Version': 'આવૃત્તિ',
      'Build Number': 'બિલ્ડ નંબર',
      'Release Year': 'પ્રકાશન વર્ષ',
      'Platform': 'પ્લેટફોર્મ',
      'Data Source': 'ડેટા સ્ત્રોત',
      'Backend': 'બેકએન્ડ',
      'Legal': 'કાનૂની',
      'Privacy Policy': 'ગોપનીયતા નીતિ',
      'Terms of Service': 'સેવાની શરતો',
      'Contact': 'સંપર્ક',
      'Acknowledgements': 'આભાર',
      'Notifications': 'સૂચનાઓ',
      'Profile': 'પ્રોફાઇલ',
      'Movies': 'ફિલ્મો',
      'Music': 'સંગીત',
      'Chat': 'ચેટ',
      'Happy': 'ખુશ',
      'Sad': 'દુઃખી',
      'Anxious': 'ચિંતિત',
      'Bored': 'કંટાળેલો',
      'Motivated': 'પ્રેરિત',
      'Romantic': 'રોમેન્ટિક',
    },

    'Punjabi': {
      'History': 'ਇਤਿਹਾਸ',
      'Favourites': 'ਮਨਪਸੰਦ',
      'Login': 'ਲੌਗ ਇਨ',
      'Logout': 'ਲੌਗ ਆਉਟ',
      'Language': 'ਭਾਸ਼ਾ',
      'Dark Mode': 'ਡਾਰਕ ਮੋਡ',
      'Help & Support': 'ਮਦਦ',
      'About Lix': 'Lix ਬਾਰੇ',
      'Selected': 'ਚੁਣਿਆ ਗਿਆ',
      'No language found': 'ਕੋਈ ਭਾਸ਼ਾ ਨਹੀਂ ਮਿਲੀ',
      'Search language...': 'ਭਾਸ਼ਾ ਖੋਜੋ...',
      'Search': 'ਖੋਜ',
      'Indian': 'ਭਾਰਤੀ',
      'Foreign': 'ਵਿਦੇਸ਼ੀ',
      'Your Top Moods': 'ਤੁਹਾਡੇ ਚੋਟੀ ਦੇ ਮੂਡ',
      'Settings': 'ਸੈਟਿੰਗਾਂ',
      'Contact Us': 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
      'FAQs': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
      'Version': 'ਵਰਜ਼ਨ',
      'Build Number': 'ਬਿਲਡ ਨੰਬਰ',
      'Release Year': 'ਰਿਲੀਜ਼ ਸਾਲ',
      'Platform': 'ਪਲੇਟਫਾਰਮ',
      'Data Source': 'ਡੇਟਾ ਸਰੋਤ',
      'Backend': 'ਬੈਕਐਂਡ',
      'Legal': 'ਕਾਨੂੰਨੀ',
      'Privacy Policy': 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
      'Terms of Service': 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
      'Contact': 'ਸੰਪਰਕ',
      'Acknowledgements': 'ਮਾਨਤਾ',
      'Notifications': 'ਸੂਚਨਾਵਾਂ',
      'Profile': 'ਪ੍ਰੋਫਾਈਲ',
      'Movies': 'ਫ਼ਿਲਮਾਂ',
      'Music': 'ਸੰਗੀਤ',
      'Chat': 'ਚੈਟ',
      'Happy': 'ਖੁਸ਼',
      'Sad': 'ਉਦਾਸ',
      'Anxious': 'ਚਿੰਤਤ',
      'Bored': 'ਅੱਕਿਆ',
      'Motivated': 'ਪ੍ਰੇਰਿਤ',
      'Romantic': 'ਰੋਮਾਂਟਿਕ',
    },

    'Odia': {
      'History': 'ଇତିହାସ',
      'Favourites': 'ପ୍ରିୟ',
      'Login': 'ଲଗ ଇନ',
      'Logout': 'ଲଗ ଆଉଟ',
      'Language': 'ଭାଷା',
      'Dark Mode': 'ଡାର୍କ ମୋଡ',
      'Help & Support': 'ସାହାଯ୍ୟ',
      'About Lix': 'Lix ବିଷୟରେ',
      'Selected': 'ମନୋନୀତ',
      'No language found': 'ଭାଷା ମିଳିଲା ନାହିଁ',
      'Search language...': 'ଭାଷା ଖୋଜ...',
      'Search': 'ଖୋଜ',
      'Indian': 'ଭାରତୀୟ',
      'Foreign': 'ବିଦେଶୀ',
      'Your Top Moods': 'ଆପଣଙ୍କ ଟପ ମୁଡ',
      'Settings': 'ସେଟିଙ୍ଗ',
      'Contact Us': 'ଆମ ସହ ଯୋଗାଯୋଗ କରନ୍ତୁ',
      'FAQs': 'ସାଧାରଣ ପ୍ରଶ୍ନ',
      'Version': 'ସଂସ୍କରଣ',
      'Build Number': 'ବିଲ୍ଡ ନମ୍ବର',
      'Release Year': 'ରିଲିଜ ବର୍ଷ',
      'Platform': 'ପ୍ଲାଟଫର୍ମ',
      'Data Source': 'ଡାଟା ଉତ୍ସ',
      'Backend': 'ବ୍ୟାକ ଏଣ୍ଡ',
      'Legal': 'ଆଇନଗତ',
      'Privacy Policy': 'ଗୋପନୀୟତା ନୀତି',
      'Terms of Service': 'ସେବା ସର୍ତ୍ତ',
      'Contact': 'ଯୋଗାଯୋଗ',
      'Acknowledgements': 'ସ୍ୱୀକୃତି',
      'Notifications': 'ବିଜ୍ଞପ୍ତି',
      'Profile': 'ପ୍ରୋଫାଇଲ',
      'Movies': 'ଚଳଚ୍ଚିତ୍ର',
      'Music': 'ସଙ୍ଗୀତ',
      'Chat': 'ଚ୍ୟାଟ',
      'Happy': 'ଖୁସି',
      'Sad': 'ଦୁଃଖୀ',
      'Anxious': 'ଚିନ୍ତିତ',
      'Bored': 'ବିରକ୍ତ',
      'Motivated': 'ପ୍ରେରିତ',
      'Romantic': 'ରୋମାଣ୍ଟିକ',
    },

    'Urdu': {
      'History': 'تاریخ',
      'Favourites': 'پسندیدہ',
      'Login': 'لاگ ان',
      'Logout': 'لاگ آؤٹ',
      'Language': 'زبان',
      'Dark Mode': 'ڈارک موڈ',
      'Help & Support': 'مدد',
      'About Lix': 'Lix کے بارے میں',
      'Selected': 'منتخب',
      'No language found': 'کوئی زبان نہیں ملی',
      'Search language...': 'زبان تلاش کریں...',
      'Search': 'تلاش',
      'Indian': 'ہندوستانی',
      'Foreign': 'غیر ملکی',
      'Your Top Moods': 'آپ کے بہترین موڈ',
      'Settings': 'ترتیبات',
      'Contact Us': 'ہم سے رابطہ کریں',
      'FAQs': 'اکثر پوچھے گئے سوالات',
      'Version': 'ورژن',
      'Build Number': 'بلڈ نمبر',
      'Release Year': 'اجراء کا سال',
      'Platform': 'پلیٹ فارم',
      'Data Source': 'ڈیٹا ماخذ',
      'Backend': 'بیک اینڈ',
      'Legal': 'قانونی',
      'Privacy Policy': 'رازداری کی پالیسی',
      'Terms of Service': 'خدمت کی شرائط',
      'Contact': 'رابطہ',
      'Acknowledgements': 'اعتراف',
      'Notifications': 'اطلاعات',
      'Profile': 'پروفائل',
      'Movies': 'فلمیں',
      'Music': 'موسیقی',
      'Chat': 'چیٹ',
      'Happy': 'خوش',
      'Sad': 'اداس',
      'Anxious': 'پریشان',
      'Bored': 'اکتایا',
      'Motivated': 'حوصلہ افزا',
      'Romantic': 'رومانٹک',
    },

    'Assamese': {
      'History': 'ইতিহাস',
      'Favourites': 'প্ৰিয়',
      'Login': 'লগ ইন',
      'Logout': 'লগ আউট',
      'Language': 'ভাষা',
      'Dark Mode': 'ডাৰ্ক মোড',
      'Help & Support': 'সহায়',
      'About Lix': 'Lix-ৰ বিষয়ে',
      'Selected': 'নিৰ্বাচিত',
      'No language found': 'কোনো ভাষা পোৱা নগ\'ল',
      'Search language...': 'ভাষা বিচাৰক...',
      'Search': 'সন্ধান',
      'Indian': 'ভাৰতীয়',
      'Foreign': 'বিদেশী',
      'Your Top Moods': 'আপোনাৰ শীৰ্ষ মুড',
      'Settings': 'ছেটিংছ',
      'Contact Us': 'আমাৰ সৈতে যোগাযোগ কৰক',
      'FAQs': 'সঘনাই সোধা প্ৰশ্ন',
      'Version': 'সংস্কৰণ',
      'Build Number': 'বিল্ড নম্বৰ',
      'Release Year': 'মুক্তিৰ বছৰ',
      'Platform': 'প্লেটফৰ্ম',
      'Data Source': 'ডেটা উৎস',
      'Backend': 'বেকএণ্ড',
      'Legal': 'আইনী',
      'Privacy Policy': 'গোপনীয়তা নীতি',
      'Terms of Service': 'সেৱাৰ চৰ্ত',
      'Contact': 'যোগাযোগ',
      'Acknowledgements': 'স্বীকৃতি',
      'Notifications': 'জাননী',
      'Profile': 'প্ৰফাইল',
      'Movies': 'চলচ্চিত্ৰ',
      'Music': 'সংগীত',
      'Chat': 'চেট',
      'Happy': 'সুখী',
      'Sad': 'দুখী',
      'Anxious': 'উদ্বিগ্ন',
      'Bored': 'বিৰক্ত',
      'Motivated': 'অনুপ্ৰাণিত',
      'Romantic': 'ৰোমান্টিক',
    },

    'Kashmiri': {
      'History': 'تأریخ',
      'Favourites': 'پسندیدہ',
      'Login': 'لاگ اِن',
      'Logout': 'لاگ آؤٹ',
      'Language': 'زبان',
      'Dark Mode': 'ڈارک موڈ',
      'Help & Support': 'مدد',
      'About Lix': 'Lix کھتہ',
      'Selected': 'چُنا',
      'No language found': 'زبان نہ مِلی',
      'Search language...': 'زبان لبُو...',
      'Search': 'تلاش',
      'Indian': 'ہندوستانی',
      'Foreign': 'بدیشی',
      'Your Top Moods': 'آپنے ٹاپ مُوڈ',
      'Settings': 'سیٹنگ',
      'Contact Us': 'آسی سیتی رابطہ',
      'FAQs': 'عام سوال',
      'Version': 'ورژن',
      'Build Number': 'بلڈ نمبر',
      'Release Year': 'سال',
      'Platform': 'پلیٹ فارم',
      'Data Source': 'ڈیٹا ذریعہ',
      'Backend': 'بیک اینڈ',
      'Legal': 'قانونی',
      'Privacy Policy': 'رازداری',
      'Terms of Service': 'شرائط',
      'Contact': 'رابطہ',
      'Acknowledgements': 'اعتراف',
      'Notifications': 'اطلاعات',
      'Profile': 'پروفائل',
      'Movies': 'فلمیں',
      'Music': 'موسیقی',
      'Chat': 'چیٹ',
      'Happy': 'خوش',
      'Sad': 'اداس',
      'Anxious': 'پریشان',
      'Bored': 'اکتایا',
      'Motivated': 'حوصلہ مند',
      'Romantic': 'رومانٹک',
    },

    'Konkani': {
      'History': 'इतिहास',
      'Favourites': 'आवडीचे',
      'Login': 'लॉगिन',
      'Logout': 'लॉगआउट',
      'Language': 'भास',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'मदत',
      'About Lix': 'Lix विशीं',
      'Selected': 'निवडिल्लें',
      'No language found': 'भास सांपडली ना',
      'Search language...': 'भास सोध...',
      'Search': 'सोध',
      'Indian': 'भारतीय',
      'Foreign': 'परकी',
      'Your Top Moods': 'तुमचे टॉप मूड',
      'Settings': 'सेटिंग्स',
      'Contact Us': 'आमकां संपर्क करा',
      'FAQs': 'वारंवार विचारिल्ले प्रस्न',
      'Version': 'आवृत्ती',
      'Build Number': 'बिल्ड क्रमांक',
      'Release Year': 'प्रकाशन वर्स',
      'Platform': 'प्लॅटफॉर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'बॅकएंड',
      'Legal': 'कायदेशीर',
      'Privacy Policy': 'गोपनीयता धोरण',
      'Terms of Service': 'सेवेच्यो अटी',
      'Contact': 'संपर्क',
      'Acknowledgements': 'आभार',
      'Notifications': 'सूचना',
      'Profile': 'प्रोफाइल',
      'Movies': 'चित्रपट',
      'Music': 'संगीत',
      'Chat': 'चॅट',
      'Happy': 'आनंदी',
      'Sad': 'दुखी',
      'Anxious': 'काळजीत',
      'Bored': 'कंटाळलेलो',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमँटिक',
    },

    'Maithili': {
      'History': 'इतिहास',
      'Favourites': 'पसिन्दीदा',
      'Login': 'लॉगिन',
      'Logout': 'लॉगआउट',
      'Language': 'भाषा',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'सहायता',
      'About Lix': 'Lix के बारे में',
      'Selected': 'चुनल गेल',
      'No language found': 'कोनो भाषा नहि भेटल',
      'Search language...': 'भाषा खोजू...',
      'Search': 'खोज',
      'Indian': 'भारतीय',
      'Foreign': 'विदेशी',
      'Your Top Moods': 'अहाँक टॉप मूड',
      'Settings': 'सेटिंग्स',
      'Contact Us': 'हमरा सँ संपर्क करू',
      'FAQs': 'सामान्य प्रश्न',
      'Version': 'संस्करण',
      'Build Number': 'बिल्ड संख्या',
      'Release Year': 'प्रकाशन वर्ष',
      'Platform': 'प्लेटफॉर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'बैकएंड',
      'Legal': 'कानूनी',
      'Privacy Policy': 'गोपनीयता नीति',
      'Terms of Service': 'सेवा शर्त',
      'Contact': 'संपर्क',
      'Acknowledgements': 'आभार',
      'Notifications': 'सूचना',
      'Profile': 'प्रोफाइल',
      'Movies': 'फिल्म',
      'Music': 'संगीत',
      'Chat': 'चैट',
      'Happy': 'खुश',
      'Sad': 'उदास',
      'Anxious': 'चिंतित',
      'Bored': 'ऊबल',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमांटिक',
    },

    'Manipuri': {
      'History': 'ꯍꯤꯁ꯭ꯇ꯭ꯔꯤ',
      'Favourites': 'ꯄ꯭ꯔꯤꯌꯥꯕ',
      'Login': 'ꯂꯣꯒ ꯏꯟ',
      'Logout': 'ꯂꯣꯒ ꯑꯥꯎꯠ',
      'Language': 'ꯂꯣꯟ',
      'Dark Mode': 'ꯗꯥꯔꯛ ꯃꯣꯗ',
      'Help & Support': 'ꯁꯔꯨꯛ',
      'About Lix': 'Lix ꯑꯃꯗꯤ',
      'Selected': 'ꯁꯦꯂꯦꯛꯇꯦꯗ',
      'No language found': 'ꯂꯣꯟ ꯑꯃꯠꯇꯥ ꯌꯥꯑꯣꯅꯤ',
      'Search language...': 'ꯂꯣꯟ ꯊꯤꯒꯠꯂꯨ...',
      'Search': 'ꯊꯤꯒꯠ',
      'Indian': 'ꯏꯟꯗꯤꯌꯥꯟ',
      'Foreign': 'ꯚꯤꯗꯦꯁꯤ',
      'Your Top Moods': 'ꯅꯪꯒꯤ ꯇꯣꯄ ꯃꯨꯗ',
      'Settings': 'ꯁꯦꯇꯤꯡ',
      'Contact Us': 'ꯑꯁꯤꯒ ꯇꯨꯡꯐꯥꯕꯤꯌꯨ',
      'FAQs': 'FAQs',
      'Version': 'ꯚꯔꯁꯅ',
      'Build Number': 'ꯕꯤꯜꯗ ꯅꯝꯕꯔ',
      'Release Year': 'ꯔꯤꯂꯤꯖ ꯆꯥꯍꯤ',
      'Platform': 'ꯄ꯭ꯂꯦꯇꯐꯣꯔꯝ',
      'Data Source': 'ꯗꯦꯇꯥ ꯁꯣꯔꯁ',
      'Backend': 'ꯕꯦꯛꯑꯦꯟꯗ',
      'Legal': 'ꯀꯥꯅꯨꯅꯤ',
      'Privacy Policy': 'ꯄ꯭ꯔꯥꯏꯚꯦꯁꯤ ꯄꯣꯂꯤꯁꯤ',
      'Terms of Service': 'ꯇꯔꯝꯁ ꯑꯚ ꯁꯔꯚꯤꯁ',
      'Contact': 'ꯇꯨꯡꯐꯥ',
      'Acknowledgements': 'ꯑꯦꯛꯅꯣꯂꯦꯖꯃꯦꯟꯇ',
      'Notifications': 'ꯅꯣꯇꯤꯐꯤꯀꯦꯁꯟ',
      'Profile': 'ꯄ꯭ꯔꯣꯐꯥꯏꯜ',
      'Movies': 'ꯐꯤꯜꯝ',
      'Music': 'ꯏꯁꯤꯡ',
      'Chat': 'ꯆꯥꯠ',
      'Happy': 'ꯈꯨꯟꯅꯔꯤꯕ',
      'Sad': 'ꯃꯔꯨꯑꯣꯏꯕ',
      'Anxious': 'ꯆꯤꯟꯇꯥꯏꯕ',
      'Bored': 'ꯀꯜꯂꯤꯕ',
      'Motivated': 'ꯍꯥꯟꯗꯣꯛꯄꯥ',
      'Romantic': 'ꯔꯣꯃꯥꯟꯇꯤꯛ',
    },

    'Nepali': {
      'History': 'इतिहास',
      'Favourites': 'मनपर्ने',
      'Login': 'लग इन',
      'Logout': 'लग आउट',
      'Language': 'भाषा',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'सहायता',
      'About Lix': 'Lix को बारेमा',
      'Selected': 'चयन गरिएको',
      'No language found': 'भाषा फेला परेन',
      'Search language...': 'भाषा खोज्नुहोस्...',
      'Search': 'खोज',
      'Indian': 'भारतीय',
      'Foreign': 'विदेशी',
      'Your Top Moods': 'तपाईंका टप मुडहरू',
      'Settings': 'सेटिङहरू',
      'Contact Us': 'हामीलाई सम्पर्क गर्नुहोस्',
      'FAQs': 'बारम्बार सोधिने प्रश्नहरू',
      'Version': 'संस्करण',
      'Build Number': 'बिल्ड नम्बर',
      'Release Year': 'रिलिज वर्ष',
      'Platform': 'प्लेटफर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'ब्याकइन्ड',
      'Legal': 'कानुनी',
      'Privacy Policy': 'गोपनीयता नीति',
      'Terms of Service': 'सेवाका सर्तहरू',
      'Contact': 'सम्पर्क',
      'Acknowledgements': 'आभार',
      'Notifications': 'सूचनाहरू',
      'Profile': 'प्रोफाइल',
      'Movies': 'चलचित्र',
      'Music': 'संगीत',
      'Chat': 'च्याट',
      'Happy': 'खुसी',
      'Sad': 'दुखी',
      'Anxious': 'चिन्तित',
      'Bored': 'बोर',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमान्टिक',
    },

    'Sanskrit': {
      'History': 'इतिहासः',
      'Favourites': 'प्रियाणि',
      'Login': 'प्रवेशः',
      'Logout': 'निर्गमः',
      'Language': 'भाषा',
      'Dark Mode': 'तमोविधा',
      'Help & Support': 'सहायता',
      'About Lix': 'Lix विषये',
      'Selected': 'चितम्',
      'No language found': 'भाषा न प्राप्ता',
      'Search language...': 'भाषां अन्विष्यतु...',
      'Search': 'अन्वेषणम्',
      'Indian': 'भारतीयम्',
      'Foreign': 'विदेशीयम्',
      'Your Top Moods': 'भवतः टॉप मूड',
      'Settings': 'व्यवस्थाः',
      'Contact Us': 'अस्मान् संपर्कयतु',
      'FAQs': 'सामान्यप्रश्नाः',
      'Version': 'संस्करणम्',
      'Build Number': 'बिल्ड संख्या',
      'Release Year': 'प्रकाशन वर्षम्',
      'Platform': 'मञ्चः',
      'Data Source': 'दत्तांशस्रोतः',
      'Backend': 'पृष्ठभागः',
      'Legal': 'विधिसम्मतम्',
      'Privacy Policy': 'गोपनीयतानीतिः',
      'Terms of Service': 'सेवाशर्ताः',
      'Contact': 'संपर्कः',
      'Acknowledgements': 'कृतज्ञता',
      'Notifications': 'सूचनाः',
      'Profile': 'परिचयः',
      'Movies': 'चलच्चित्रम्',
      'Music': 'संगीतम्',
      'Chat': 'वार्तालापः',
      'Happy': 'प्रसन्नः',
      'Sad': 'दुःखितः',
      'Anxious': 'चिन्तितः',
      'Bored': 'उद्विग्नः',
      'Motivated': 'प्रेरितः',
      'Romantic': 'रोमाञ्चकः',
    },

    'Santali': {
      'History': 'ᱤᱛᱤᱦᱟᱥ',
      'Favourites': 'ᱢᱚᱱ ᱞᱟᱹᱜᱤᱫ',
      'Login': 'ᱞᱚᱜ ᱤᱱ',
      'Logout': 'ᱞᱚᱜ ᱟᱹᱣᱴ',
      'Language': 'ᱯᱷᱟᱱ',
      'Dark Mode': 'ᱫᱟᱨᱠ ᱢᱳᱰ',
      'Help & Support': 'ᱢᱟᱲᱟᱝ',
      'About Lix': 'Lix ᱥᱟᱶᱛᱮ',
      'Selected': 'ᱵᱟᱪᱷᱟᱣ ᱦᱩᱭ',
      'No language found': 'ᱯᱷᱟᱱ ᱵᱟᱦᱟ ᱢᱮᱫ',
      'Search language...': 'ᱯᱷᱟᱱ ᱧᱮᱞ...',
      'Search': 'ᱧᱮᱞ',
      'Indian': 'ᱥᱤᱧ ᱫᱷᱟᱨᱛᱤ',
      'Foreign': 'ᱵᱤᱫᱮᱥᱤ',
      'Your Top Moods': 'ᱟᱢᱟᱜ ᱴᱚᱯ ᱢᱩᱰ',
      'Settings': 'ᱥᱮᱴᱤᱝ',
      'Contact Us': 'ᱟᱢᱟᱜ ᱥᱟᱶ ᱡᱚᱜᱟᱣ',
      'FAQs': 'FAQs',
      'Version': 'ᱵᱷᱟᱥᱚᱱ',
      'Build Number': 'ᱵᱤᱞᱰ ᱱᱚᱝᱵᱚᱨ',
      'Release Year': 'ᱨᱤᱞᱤᱡ ᱥᱮᱨᱢᱟ',
      'Platform': 'ᱯᱞᱮᱴᱯᱷᱚᱨᱢ',
      'Data Source': 'ᱰᱮᱴᱟ ᱥᱳᱨᱥ',
      'Backend': 'ᱵᱮᱠᱮᱱᱰ',
      'Legal': 'ᱞᱤᱜᱮᱞ',
      'Privacy Policy': 'ᱯᱨᱟᱭᱵᱷᱮᱥᱤ ᱱᱤᱛᱤ',
      'Terms of Service': 'ᱥᱮᱵᱟ ᱪᱟᱹᱨᱤᱫ',
      'Contact': 'ᱡᱚᱜᱟᱣ',
      'Acknowledgements': 'ᱢᱟᱱᱽᱛᱟ',
      'Notifications': 'ᱥᱩᱪᱚᱱᱟ',
      'Profile': 'ᱯᱨᱚᱯᱷᱟᱭᱞ',
      'Movies': 'ᱯᱷᱤᱞᱢ',
      'Music': 'ᱮᱞᱮᱝ',
      'Chat': 'ᱪᱮᱴ',
      'Happy': 'ᱥᱟᱧᱦᱟᱣ',
      'Sad': 'ᱫᱩᱠᱷᱤ',
      'Anxious': 'ᱪᱤᱱᱛᱟ',
      'Bored': 'ᱠᱚᱞᱟ',
      'Motivated': 'ᱯᱨᱮᱨᱟᱱᱟ',
      'Romantic': 'ᱨᱳᱢᱟᱱᱴᱤᱠ',
    },

    'Sindhi': {
      'History': 'تاريخ',
      'Favourites': 'پسنديدو',
      'Login': 'لاگ اِن',
      'Logout': 'لاگ آئوٽ',
      'Language': 'ٻولي',
      'Dark Mode': 'ڊارڪ موڊ',
      'Help & Support': 'مدد',
      'About Lix': 'Lix بابت',
      'Selected': 'چونڊيل',
      'No language found': 'ڪا ٻولي نه مليو',
      'Search language...': 'ٻولي ڳولهيو...',
      'Search': 'ڳولها',
      'Indian': 'هندستاني',
      'Foreign': 'پرديسي',
      'Your Top Moods': 'توهانجا ٽاپ موڊ',
      'Settings': 'سيٽنگون',
      'Contact Us': 'اسان سان رابطو ڪريو',
      'FAQs': 'عام سوال',
      'Version': 'ورجن',
      'Build Number': 'بلڊ نمبر',
      'Release Year': 'جاري سال',
      'Platform': 'پليٽ فارم',
      'Data Source': 'ڊيٽا ذريعو',
      'Backend': 'بيڪ اينڊ',
      'Legal': 'قانوني',
      'Privacy Policy': 'رازداري پاليسي',
      'Terms of Service': 'خدمت جون شرطون',
      'Contact': 'رابطو',
      'Acknowledgements': 'اعتراف',
      'Notifications': 'اطلاع',
      'Profile': 'پروفائل',
      'Movies': 'فلمون',
      'Music': 'موسيقي',
      'Chat': 'چيٽ',
      'Happy': 'خوش',
      'Sad': 'اداس',
      'Anxious': 'پريشان',
      'Bored': 'اکتايل',
      'Motivated': 'حوصلو',
      'Romantic': 'رومانٽڪ',
    },

    'Bodo': {
      'History': 'इतिहास',
      'Favourites': 'फेवरिट',
      'Login': 'लग इन',
      'Logout': 'लग आउट',
      'Language': 'होबा',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'सोमोन्दो',
      'About Lix': 'Lix सोमोन्दो',
      'Selected': 'बायनाय',
      'No language found': 'होबा मोनाय',
      'Search language...': 'होबा नायगौ...',
      'Search': 'नायगौ',
      'Indian': 'भारतीय',
      'Foreign': 'बिदेशी',
      'Your Top Moods': 'नों टॉप मूड',
      'Settings': 'सेटिंग',
      'Contact Us': 'हानजावगौ',
      'FAQs': 'FAQs',
      'Version': 'भार्सन',
      'Build Number': 'बिल्ड नम्बर',
      'Release Year': 'हिनजाव बोसर',
      'Platform': 'प्लेटफर्म',
      'Data Source': 'डेटा सोर्स',
      'Backend': 'बैकएन्ड',
      'Legal': 'आइन',
      'Privacy Policy': 'गोपनीयता नीति',
      'Terms of Service': 'सेवा शर्त',
      'Contact': 'हानजावगौ',
      'Acknowledgements': 'आभार',
      'Notifications': 'सूचना',
      'Profile': 'प्रोफाइल',
      'Movies': 'फिल्म',
      'Music': 'संगीत',
      'Chat': 'चैट',
      'Happy': 'आनन्द',
      'Sad': 'दुखु',
      'Anxious': 'चिन्ता',
      'Bored': 'मोनसे',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमांटिक',
    },

    'Dogri': {
      'History': 'इतिहास',
      'Favourites': 'पसंदीदा',
      'Login': 'लॉगिन',
      'Logout': 'लॉगआउट',
      'Language': 'बोली',
      'Dark Mode': 'डार्क मोड',
      'Help & Support': 'मदद',
      'About Lix': 'Lix दे बारे च',
      'Selected': 'चुनेआ',
      'No language found': 'कोई बोली नेईं मिली',
      'Search language...': 'बोली लब्भो...',
      'Search': 'लब्भो',
      'Indian': 'भारतीय',
      'Foreign': 'विदेशी',
      'Your Top Moods': 'तुंडे टॉप मूड',
      'Settings': 'सेटिंग्स',
      'Contact Us': 'संपर्क करो',
      'FAQs': 'FAQs',
      'Version': 'संस्करण',
      'Build Number': 'बिल्ड नंबर',
      'Release Year': 'रिलीज साल',
      'Platform': 'प्लेटफॉर्म',
      'Data Source': 'डेटा स्रोत',
      'Backend': 'बैकएंड',
      'Legal': 'कानूनी',
      'Privacy Policy': 'गोपनीयता नीति',
      'Terms of Service': 'सेवा नियम',
      'Contact': 'संपर्क',
      'Acknowledgements': 'शुक्रिया',
      'Notifications': 'सूचना',
      'Profile': 'प्रोफाइल',
      'Movies': 'फिल्म',
      'Music': 'संगीत',
      'Chat': 'चैट',
      'Happy': 'खुश',
      'Sad': 'उदास',
      'Anxious': 'चिंतत',
      'Bored': 'अक्कना',
      'Motivated': 'प्रेरित',
      'Romantic': 'रोमांटिक',
    },

    'Mandarin': {
      'History': '历史',
      'Favourites': '收藏',
      'Login': '登录',
      'Logout': '退出',
      'Language': '语言',
      'Dark Mode': '深色模式',
      'Help & Support': '帮助',
      'About Lix': '关于Lix',
      'Selected': '已选择',
      'No language found': '未找到语言',
      'Search language...': '搜索语言...',
      'Search': '搜索',
      'Indian': '印度',
      'Foreign': '外国',
      'Your Top Moods': '您的热门情绪',
      'Settings': '设置',
      'Contact Us': '联系我们',
      'FAQs': '常见问题',
      'Version': '版本',
      'Build Number': '构建号',
      'Release Year': '发布年份',
      'Platform': '平台',
      'Data Source': '数据来源',
      'Backend': '后端',
      'Legal': '法律',
      'Privacy Policy': '隐私政策',
      'Terms of Service': '服务条款',
      'Contact': '联系',
      'Acknowledgements': '致谢',
      'Notifications': '通知',
      'Profile': '个人资料',
      'Movies': '电影',
      'Music': '音乐',
      'Chat': '聊天',
      'Happy': '快乐',
      'Sad': '悲伤',
      'Anxious': '焦虑',
      'Bored': '无聊',
      'Motivated': '积极',
      'Romantic': '浪漫',
    },

    'Spanish': {
      'History': 'Historial',
      'Favourites': 'Favoritos',
      'Login': 'Iniciar sesión',
      'Logout': 'Cerrar sesión',
      'Language': 'Idioma',
      'Dark Mode': 'Modo oscuro',
      'Help & Support': 'Ayuda',
      'About Lix': 'Sobre Lix',
      'Selected': 'Seleccionado',
      'No language found': 'No se encontró idioma',
      'Search language...': 'Buscar idioma...',
      'Search': 'Buscar',
      'Indian': 'Indio',
      'Foreign': 'Extranjero',
      'Your Top Moods': 'Tus mejores estados de ánimo',
      'Settings': 'Configuración',
      'Contact Us': 'Contáctanos',
      'FAQs': 'Preguntas frecuentes',
      'Version': 'Versión',
      'Build Number': 'Número de build',
      'Release Year': 'Año de lanzamiento',
      'Platform': 'Plataforma',
      'Data Source': 'Fuente de datos',
      'Backend': 'Backend',
      'Legal': 'Legal',
      'Privacy Policy': 'Política de privacidad',
      'Terms of Service': 'Términos de servicio',
      'Contact': 'Contacto',
      'Acknowledgements': 'Agradecimientos',
      'Notifications': 'Notificaciones',
      'Profile': 'Perfil',
      'Movies': 'Películas',
      'Music': 'Música',
      'Chat': 'Chat',
      'Happy': 'Feliz',
      'Sad': 'Triste',
      'Anxious': 'Ansioso',
      'Bored': 'Aburrido',
      'Motivated': 'Motivado',
      'Romantic': 'Romántico',
    },

    'French': {
      'History': 'Historique',
      'Favourites': 'Favoris',
      'Login': 'Connexion',
      'Logout': 'Déconnexion',
      'Language': 'Langue',
      'Dark Mode': 'Mode sombre',
      'Help & Support': 'Aide',
      'About Lix': 'À propos de Lix',
      'Selected': 'Sélectionné',
      'No language found': 'Aucune langue trouvée',
      'Search language...': 'Rechercher une langue...',
      'Search': 'Rechercher',
      'Indian': 'Indien',
      'Foreign': 'Étranger',
      'Your Top Moods': 'Vos meilleures humeurs',
      'Settings': 'Paramètres',
      'Contact Us': 'Contactez-nous',
      'FAQs': 'F.A.Q.',
      'Version': 'Version',
      'Build Number': 'Numéro de build',
      'Release Year': 'Année de sortie',
      'Platform': 'Plateforme',
      'Data Source': 'Source de données',
      'Backend': 'Backend',
      'Legal': 'Légal',
      'Privacy Policy': 'Politique de confidentialité',
      'Terms of Service': 'Conditions d\'utilisation',
      'Contact': 'Contact',
      'Acknowledgements': 'Remerciements',
      'Notifications': 'Notifications',
      'Profile': 'Profil',
      'Movies': 'Films',
      'Music': 'Musique',
      'Chat': 'Discussion',
      'Happy': 'Heureux',
      'Sad': 'Triste',
      'Anxious': 'Anxieux',
      'Bored': 'Ennuyé',
      'Motivated': 'Motivé',
      'Romantic': 'Romantique',
    },

    'Arabic': {
      'History': 'السجل',
      'Favourites': 'المفضلة',
      'Login': 'تسجيل الدخول',
      'Logout': 'تسجيل الخروج',
      'Language': 'اللغة',
      'Dark Mode': 'الوضع الداكن',
      'Help & Support': 'الدعم',
      'About Lix': 'حول Lix',
      'Selected': 'مختارة',
      'No language found': 'لا توجد لغة',
      'Search language...': 'ابحث عن لغة...',
      'Search': 'بحث',
      'Indian': 'الهندية',
      'Foreign': 'الأجنبية',
      'Your Top Moods': 'أفضل حالاتك المزاجية',
      'Settings': 'الإعدادات',
      'Contact Us': 'اتصل بنا',
      'FAQs': 'الأسئلة الشائعة',
      'Version': 'الإصدار',
      'Build Number': 'رقم البناء',
      'Release Year': 'سنة الإصدار',
      'Platform': 'المنصة',
      'Data Source': 'مصدر البيانات',
      'Backend': 'الخلفية',
      'Legal': 'القانونية',
      'Privacy Policy': 'سياسة الخصوصية',
      'Terms of Service': 'شروط الخدمة',
      'Contact': 'اتصال',
      'Acknowledgements': 'الإقرار بالفضل',
      'Notifications': 'الإشعارات',
      'Profile': 'الملف الشخصي',
      'Movies': 'أفلام',
      'Music': 'موسيقى',
      'Chat': 'محادثة',
      'Happy': 'سعيد',
      'Sad': 'حزين',
      'Anxious': 'قلق',
      'Bored': 'يشعر بالملل',
      'Motivated': 'متحمس',
      'Romantic': 'رومانسي',
    },

    'Portuguese': {
      'History': 'Histórico',
      'Favourites': 'Favoritos',
      'Login': 'Entrar',
      'Logout': 'Sair',
      'Language': 'Idioma',
      'Dark Mode': 'Modo escuro',
      'Help & Support': 'Ajuda',
      'About Lix': 'Sobre o Lix',
      'Selected': 'Selecionado',
      'No language found': 'Nenhuma língua encontrada',
      'Search language...': 'Pesquisar idioma...',
      'Search': 'Pesquisar',
      'Indian': 'Indiano',
      'Foreign': 'Estrangeiro',
      'Your Top Moods': 'Seus principais humores',
      'Settings': 'Configurações',
      'Contact Us': 'Entre em contato',
      'FAQs': 'Perguntas frequentes',
      'Version': 'Versão',
      'Build Number': 'Número do build',
      'Release Year': 'Ano de lançamento',
      'Platform': 'Plataforma',
      'Data Source': 'Fonte de dados',
      'Backend': 'Backend',
      'Legal': 'Legal',
      'Privacy Policy': 'Política de Privacidade',
      'Terms of Service': 'Termos de Serviço',
      'Contact': 'Contato',
      'Acknowledgements': 'Agradecimentos',
      'Notifications': 'Notificações',
      'Profile': 'Perfil',
      'Movies': 'Filmes',
      'Music': 'Música',
      'Chat': 'Bate-papo',
      'Happy': 'Feliz',
      'Sad': 'Triste',
      'Anxious': 'Ansioso',
      'Bored': 'Entediado',
      'Motivated': 'Motivado',
      'Romantic': 'Romântico',
    },

    'Russian': {
      'History': 'История',
      'Favourites': 'Избранное',
      'Login': 'Войти',
      'Logout': 'Выйти',
      'Language': 'Язык',
      'Dark Mode': 'Тёмный режим',
      'Help & Support': 'Помощь',
      'About Lix': 'О Lix',
      'Selected': 'Выбрано',
      'No language found': 'Язык не найден',
      'Search language...': 'Поиск языка...',
      'Search': 'Поиск',
      'Indian': 'Индийский',
      'Foreign': 'Иностранный',
      'Your Top Moods': 'Ваши лучшие настроения',
      'Settings': 'Настройки',
      'Contact Us': 'Связаться',
      'FAQs': 'Часто задаваемые вопросы',
      'Version': 'Версия',
      'Build Number': 'Номер сборки',
      'Release Year': 'Год выпуска',
      'Platform': 'Платформа',
      'Data Source': 'Источник данных',
      'Backend': 'Бэкенд',
      'Legal': 'Правовая информация',
      'Privacy Policy': 'Политика конфиденциальности',
      'Terms of Service': 'Условия использования',
      'Contact': 'Контакт',
      'Acknowledgements': 'Благодарность',
      'Notifications': 'Уведомления',
      'Profile': 'Профиль',
      'Movies': 'Фильмы',
      'Music': 'Музыка',
      'Chat': 'Чат',
      'Happy': 'Счастливый',
      'Sad': 'Грустный',
      'Anxious': 'Тревожный',
      'Bored': 'Скучающий',
      'Motivated': 'Мотивированный',
      'Romantic': 'Романтичный',
    },

    'Japanese': {
      'History': '履歴',
      'Favourites': 'お気に入り',
      'Login': 'ログイン',
      'Logout': 'ログアウト',
      'Language': '言語',
      'Dark Mode': 'ダークモード',
      'Help & Support': 'ヘルプ',
      'About Lix': 'Lixについて',
      'Selected': '選択済み',
      'No language found': '言語が見つかりません',
      'Search language...': '言語を検索...',
      'Search': '検索',
      'Indian': 'インド',
      'Foreign': '外国',
      'Your Top Moods': 'トップムード',
      'Settings': '設定',
      'Contact Us': 'お問い合わせ',
      'FAQs': 'よくある質問',
      'Version': 'バージョン',
      'Build Number': 'ビルド番号',
      'Release Year': 'リリース年',
      'Platform': 'プラットフォーム',
      'Data Source': 'データソース',
      'Backend': 'バックエンド',
      'Legal': '法律',
      'Privacy Policy': 'プライバシーポリシー',
      'Terms of Service': '利用規約',
      'Contact': '連絡先',
      'Acknowledgements': '謝辞',
      'Notifications': '通知',
      'Profile': 'プロフィール',
      'Movies': '映画',
      'Music': '音楽',
      'Chat': 'チャット',
      'Happy': '幸せ',
      'Sad': '悲しい',
      'Anxious': '不安',
      'Bored': '退屈',
      'Motivated': 'やる気',
      'Romantic': 'ロマンチック',
    },

    'German': {
      'History': 'Verlauf',
      'Favourites': 'Favoriten',
      'Login': 'Einloggen',
      'Logout': 'Abmelden',
      'Language': 'Sprache',
      'Dark Mode': 'Dunkler Modus',
      'Help & Support': 'Hilfe',
      'About Lix': 'Über Lix',
      'Selected': 'Ausgewählt',
      'No language found': 'Keine Sprache gefunden',
      'Search language...': 'Sprache suchen...',
      'Search': 'Suchen',
      'Indian': 'Indisch',
      'Foreign': 'Ausländisch',
      'Your Top Moods': 'Ihre Top‑Stimmungen',
      'Settings': 'Einstellungen',
      'Contact Us': 'Kontakt',
      'FAQs': 'Häufige Fragen',
      'Version': 'Version',
      'Build Number': 'Build‑Nummer',
      'Release Year': 'Erscheinungsjahr',
      'Platform': 'Plattform',
      'Data Source': 'Datenquelle',
      'Backend': 'Backend',
      'Legal': 'Rechtliches',
      'Privacy Policy': 'Datenschutzrichtlinie',
      'Terms of Service': 'Nutzungsbedingungen',
      'Contact': 'Kontakt',
      'Acknowledgements': 'Dank',
      'Notifications': 'Benachrichtigungen',
      'Profile': 'Profil',
      'Movies': 'Filme',
      'Music': 'Musik',
      'Chat': 'Chat',
      'Happy': 'Glücklich',
      'Sad': 'Traurig',
      'Anxious': 'Ängstlich',
      'Bored': 'Gelangweilt',
      'Motivated': 'Motiviert',
      'Romantic': 'Romantisch',
    },

    'Korean': {
      'History': '기록',
      'Favourites': '즐겨찾기',
      'Login': '로그인',
      'Logout': '로그아웃',
      'Language': '언어',
      'Dark Mode': '다크 모드',
      'Help & Support': '도움말',
      'About Lix': 'Lix 정보',
      'Selected': '선택됨',
      'No language found': '언어를 찾을 수 없음',
      'Search language...': '언어 찾기...',
      'Search': '검색',
      'Indian': '인도',
      'Foreign': '외국',
      'Your Top Moods': '최고 기분',
      'Settings': '설정',
      'Contact Us': '연락처',
      'FAQs': '자주 묻는 질문',
      'Version': '버전',
      'Build Number': '빌드 번호',
      'Release Year': '출시 연도',
      'Platform': '플랫폼',
      'Data Source': '데이터 소스',
      'Backend': '백엔드',
      'Legal': '법률',
      'Privacy Policy': '개인정보 처리방침',
      'Terms of Service': '서비스 이용약관',
      'Contact': '연락처',
      'Acknowledgements': '감사의 말',
      'Notifications': '알림',
      'Profile': '프로필',
      'Movies': '영화',
      'Music': '음악',
      'Chat': '채팅',
      'Happy': '행복',
      'Sad': '슬픔',
      'Anxious': '불안',
      'Bored': '지루함',
      'Motivated': '동기부여',
      'Romantic': '로맨틱',
    },

    'Italian': {
      'History': 'Cronologia',
      'Favourites': 'Preferiti',
      'Login': 'Accedi',
      'Logout': 'Esci',
      'Language': 'Lingua',
      'Dark Mode': 'Modalità scura',
      'Help & Support': 'Assistenza',
      'About Lix': 'Informazioni su Lix',
      'Selected': 'Selezionato',
      'No language found': 'Nessuna lingua trovata',
      'Search language...': 'Cerca lingua...',
      'Search': 'Cerca',
      'Indian': 'Indiano',
      'Foreign': 'Straniero',
      'Your Top Moods': 'I tuoi stati d\'animo',
      'Settings': 'Impostazioni',
      'Contact Us': 'Contattaci',
      'FAQs': 'Domande frequenti',
      'Version': 'Versione',
      'Build Number': 'Numero build',
      'Release Year': 'Anno di rilascio',
      'Platform': 'Piattaforma',
      'Data Source': 'Fonte dati',
      'Backend': 'Backend',
      'Legal': 'Legale',
      'Privacy Policy': 'Informativa sulla privacy',
      'Terms of Service': 'Termini di servizio',
      'Contact': 'Contatto',
      'Acknowledgements': 'Ringraziamenti',
      'Notifications': 'Notifiche',
      'Profile': 'Profilo',
      'Movies': 'Film',
      'Music': 'Musica',
      'Chat': 'Chat',
      'Happy': 'Felice',
      'Sad': 'Triste',
      'Anxious': 'Ansioso',
      'Bored': 'Annoiato',
      'Motivated': 'Motivato',
      'Romantic': 'Romantico',
    },

    'Turkish': {
      'History': 'Geçmiş',
      'Favourites': 'Favoriler',
      'Login': 'Giriş Yap',
      'Logout': 'Çıkış Yap',
      'Language': 'Dil',
      'Dark Mode': 'Karanlık Mod',
      'Help & Support': 'Yardım',
      'About Lix': 'Lix Hakkında',
      'Selected': 'Seçildi',
      'No language found': 'Dil bulunamadı',
      'Search language...': 'Dil ara...',
      'Search': 'Ara',
      'Indian': 'Hintli',
      'Foreign': 'Yabancı',
      'Your Top Moods': 'En İyi Ruh Hallerin',
      'Settings': 'Ayarlar',
      'Contact Us': 'Bize Ulaşın',
      'FAQs': 'Sık Sorulan Sorular',
      'Version': 'Sürüm',
      'Build Number': 'Derleme Numarası',
      'Release Year': 'Yayın Yılı',
      'Platform': 'Platform',
      'Data Source': 'Veri Kaynağı',
      'Backend': 'Arka Uç',
      'Legal': 'Yasal',
      'Privacy Policy': 'Gizlilik Politikası',
      'Terms of Service': 'Hizmet Şartları',
      'Contact': 'İletişim',
      'Acknowledgements': 'Teşekkürler',
      'Notifications': 'Bildirimler',
      'Profile': 'Profil',
      'Movies': 'Filmler',
      'Music': 'Müzik',
      'Chat': 'Sohbet',
      'Happy': 'Mutlu',
      'Sad': 'Üzgün',
      'Anxious': 'Endişeli',
      'Bored': 'Sıkılmış',
      'Motivated': 'Motive',
      'Romantic': 'Romantik',
    },

    'Dutch': {
      'History': 'Geschiedenis',
      'Favourites': 'Favorieten',
      'Login': 'Inloggen',
      'Logout': 'Uitloggen',
      'Language': 'Taal',
      'Dark Mode': 'Donkere modus',
      'Help & Support': 'Hulp',
      'About Lix': 'Over Lix',
      'Selected': 'Geselecteerd',
      'No language found': 'Geen taal gevonden',
      'Search language...': 'Taal zoeken...',
      'Search': 'Zoeken',
      'Indian': 'Indisch',
      'Foreign': 'Buitenlands',
      'Your Top Moods': 'Jouw topstemmingen',
      'Settings': 'Instellingen',
      'Contact Us': 'Neem contact op',
      'FAQs': 'Veelgestelde vragen',
      'Version': 'Versie',
      'Build Number': 'Buildnummer',
      'Release Year': 'Uitgavejaar',
      'Platform': 'Platform',
      'Data Source': 'Gegevensbron',
      'Backend': 'Backend',
      'Legal': 'Juridisch',
      'Privacy Policy': 'Privacybeleid',
      'Terms of Service': 'Servicevoorwaarden',
      'Contact': 'Contact',
      'Acknowledgements': 'Dankwoord',
      'Notifications': 'Meldingen',
      'Profile': 'Profiel',
      'Movies': 'Films',
      'Music': 'Muziek',
      'Chat': 'Chat',
      'Happy': 'Blij',
      'Sad': 'Verdrietig',
      'Anxious': 'Angstig',
      'Bored': 'Verveeld',
      'Motivated': 'Gemotiveerd',
      'Romantic': 'Romantisch',
    },

    'Polish': {
      'History': 'Historia',
      'Favourites': 'Ulubione',
      'Login': 'Zaloguj się',
      'Logout': 'Wyloguj się',
      'Language': 'Język',
      'Dark Mode': 'Tryb ciemny',
      'Help & Support': 'Pomoc',
      'About Lix': 'O Lix',
      'Selected': 'Wybrano',
      'No language found': 'Nie znaleziono języka',
      'Search language...': 'Szukaj języka...',
      'Search': 'Szukaj',
      'Indian': 'Indyjski',
      'Foreign': 'Zagraniczny',
      'Your Top Moods': 'Twoje najlepsze nastroje',
      'Settings': 'Ustawienia',
      'Contact Us': 'Skontaktuj się z nami',
      'FAQs': 'Często zadawane pytania',
      'Version': 'Wersja',
      'Build Number': 'Numer buildu',
      'Release Year': 'Rok wydania',
      'Platform': 'Platforma',
      'Data Source': 'Źródło danych',
      'Backend': 'Backend',
      'Legal': 'Prawne',
      'Privacy Policy': 'Polityka prywatności',
      'Terms of Service': 'Warunki usługi',
      'Contact': 'Kontakt',
      'Acknowledgements': 'Podziękowania',
      'Notifications': 'Powiadomienia',
      'Profile': 'Profil',
      'Movies': 'Filmy',
      'Music': 'Muzyka',
      'Chat': 'Czat',
      'Happy': 'Szczęśliwy',
      'Sad': 'Smutny',
      'Anxious': 'Niespokojny',
      'Bored': 'Znudzony',
      'Motivated': 'Zmotywowany',
      'Romantic': 'Romantyczny',
    },

    'Swedish': {
      'History': 'Historik',
      'Favourites': 'Favoriter',
      'Login': 'Logga in',
      'Logout': 'Logga ut',
      'Language': 'Språk',
      'Dark Mode': 'Mörkt läge',
      'Help & Support': 'Hjälp',
      'About Lix': 'Om Lix',
      'Selected': 'Vald',
      'No language found': 'Inget språk hittades',
      'Search language...': 'Sök språk...',
      'Search': 'Sök',
      'Indian': 'Indisk',
      'Foreign': 'Utländsk',
      'Your Top Moods': 'Dina bästa humör',
      'Settings': 'Inställningar',
      'Contact Us': 'Kontakta oss',
      'FAQs': 'Vanliga frågor',
      'Version': 'Version',
      'Build Number': 'Buildnummer',
      'Release Year': 'Utgivningsår',
      'Platform': 'Plattform',
      'Data Source': 'Datakälla',
      'Backend': 'Backend',
      'Legal': 'Juridiskt',
      'Privacy Policy': 'Integritetspolicy',
      'Terms of Service': 'Användarvillkor',
      'Contact': 'Kontakt',
      'Acknowledgements': 'Tack',
      'Notifications': 'Aviseringar',
      'Profile': 'Profil',
      'Movies': 'Filmer',
      'Music': 'Musik',
      'Chat': 'Chatt',
      'Happy': 'Glad',
      'Sad': 'Ledsen',
      'Anxious': 'Orolig',
      'Bored': 'Uttråkad',
      'Motivated': 'Motiverad',
      'Romantic': 'Romantisk',
    },

    'Greek': {
      'History': 'Ιστορικό',
      'Favourites': 'Αγαπημένα',
      'Login': 'Σύνδεση',
      'Logout': 'Αποσύνδεση',
      'Language': 'Γλώσσα',
      'Dark Mode': 'Σκοτεινή λειτουργία',
      'Help & Support': 'Βοήθεια',
      'About Lix': 'Σχετικά με το Lix',
      'Selected': 'Επιλεγμένο',
      'No language found': 'Δεν βρέθηκε γλώσσα',
      'Search language...': 'Αναζήτηση γλώσσας...',
      'Search': 'Αναζήτηση',
      'Indian': 'Ινδικός',
      'Foreign': 'Ξένος',
      'Your Top Moods': 'Τα κορυφαία σου διαθέσεις',
      'Settings': 'Ρυθμίσεις',
      'Contact Us': 'Επικοινωνήστε μαζί μας',
      'FAQs': 'Συχνές ερωτήσεις',
      'Version': 'Έκδοση',
      'Build Number': 'Αριθμός έκδοσης',
      'Release Year': 'Έτος κυκλοφορίας',
      'Platform': 'Πλατφόρμα',
      'Data Source': 'Πηγή δεδομένων',
      'Backend': 'Backend',
      'Legal': 'Νομικό',
      'Privacy Policy': 'Πολιτική απορρήτου',
      'Terms of Service': 'Όροι υπηρεσίας',
      'Contact': 'Επικοινωνία',
      'Acknowledgements': 'Ευχαριστίες',
      'Notifications': 'Ειδοποιήσεις',
      'Profile': 'Προφίλ',
      'Movies': 'Ταινίες',
      'Music': 'Μουσική',
      'Chat': 'Συνομιλία',
      'Happy': 'Χαρούμενος',
      'Sad': 'Λυπημένος',
      'Anxious': 'Ανήσυχος',
      'Bored': 'Βαριεστημένος',
      'Motivated': 'Παρακινημένος',
      'Romantic': 'Ρομαντικός',
    },

    'Hebrew': {
      'History': 'היסטוריה',
      'Favourites': 'מועדפים',
      'Login': 'התחברות',
      'Logout': 'התנתקות',
      'Language': 'שפה',
      'Dark Mode': 'מצב כהה',
      'Help & Support': 'עזרה',
      'About Lix': 'אודות Lix',
      'Selected': 'נבחר',
      'No language found': 'לא נמצאה שפה',
      'Search language...': 'חיפוש שפה...',
      'Search': 'חיפוש',
      'Indian': 'הודי',
      'Foreign': 'זר',
      'Your Top Moods': 'מצבי הרוח המובילים שלך',
      'Settings': 'הגדרות',
      'Contact Us': 'צור קשר',
      'FAQs': 'שאלות נפוצות',
      'Version': 'גרסה',
      'Build Number': 'מספר גרסת בנייה',
      'Release Year': 'שנת הוצאה',
      'Platform': 'פלטפורמה',
      'Data Source': 'מקור נתונים',
      'Backend': 'צד שרת',
      'Legal': 'משפטי',
      'Privacy Policy': 'מדיניות פרטיות',
      'Terms of Service': 'תנאי שימוש',
      'Contact': 'יצירת קשר',
      'Acknowledgements': 'תודות',
      'Notifications': 'התראות',
      'Profile': 'פרופיל',
      'Movies': 'סרטים',
      'Music': 'מוזיקה',
      'Chat': 'צ\'אט',
      'Happy': 'שמח',
      'Sad': 'עצוב',
      'Anxious': 'חרד',
      'Bored': 'משועמם',
      'Motivated': 'מוטיבציה',
      'Romantic': 'רומנטי',
    },

    'Thai': {
      'History': 'ประวัติ',
      'Favourites': 'รายการโปรด',
      'Login': 'เข้าสู่ระบบ',
      'Logout': 'ออกจากระบบ',
      'Language': 'ภาษา',
      'Dark Mode': 'โหมดมืด',
      'Help & Support': 'ช่วยเหลือ',
      'About Lix': 'เกี่ยวกับ Lix',
      'Selected': 'เลือกแล้ว',
      'No language found': 'ไม่พบภาษา',
      'Search language...': 'ค้นหาภาษา...',
      'Search': 'ค้นหา',
      'Indian': 'อินเดีย',
      'Foreign': 'ต่างประเทศ',
      'Your Top Moods': 'อารมณ์ยอดนิยมของคุณ',
      'Settings': 'การตั้งค่า',
      'Contact Us': 'ติดต่อเรา',
      'FAQs': 'คำถามที่พบบ่อย',
      'Version': 'เวอร์ชัน',
      'Build Number': 'หมายเลขบิลด์',
      'Release Year': 'ปีที่วางจำหน่าย',
      'Platform': 'แพลตฟอร์ม',
      'Data Source': 'แหล่งข้อมูล',
      'Backend': 'แบ็กเอนด์',
      'Legal': 'กฎหมาย',
      'Privacy Policy': 'นโยบายความเป็นส่วนตัว',
      'Terms of Service': 'ข้อกำหนดการใช้บริการ',
      'Contact': 'ติดต่อ',
      'Acknowledgements': 'กิตติกรรมประกาศ',
      'Notifications': 'การแจ้งเตือน',
      'Profile': 'โปรไฟล์',
      'Movies': 'ภาพยนตร์',
      'Music': 'เพลง',
      'Chat': 'แชท',
      'Happy': 'มีความสุข',
      'Sad': 'เศร้า',
      'Anxious': 'วิตกกังวล',
      'Bored': 'เบื่อ',
      'Motivated': 'มีแรงบันดาลใจ',
      'Romantic': 'โรแมนติก',
    },

    'Vietnamese': {
      'History': 'Lịch sử',
      'Favourites': 'Yêu thích',
      'Login': 'Đăng nhập',
      'Logout': 'Đăng xuất',
      'Language': 'Ngôn ngữ',
      'Dark Mode': 'Chế độ tối',
      'Help & Support': 'Trợ giúp',
      'About Lix': 'Giới thiệu Lix',
      'Selected': 'Đã chọn',
      'No language found': 'Không tìm thấy ngôn ngữ',
      'Search language...': 'Tìm kiếm ngôn ngữ...',
      'Search': 'Tìm kiếm',
      'Indian': 'Ấn Độ',
      'Foreign': 'Nước ngoài',
      'Your Top Moods': 'Tâm trạng hàng đầu của bạn',
      'Settings': 'Cài đặt',
      'Contact Us': 'Liên hệ chúng tôi',
      'FAQs': 'Câu hỏi thường gặp',
      'Version': 'Phiên bản',
      'Build Number': 'Số bản dựng',
      'Release Year': 'Năm phát hành',
      'Platform': 'Nền tảng',
      'Data Source': 'Nguồn dữ liệu',
      'Backend': 'Backend',
      'Legal': 'Pháp lý',
      'Privacy Policy': 'Chính sách bảo mật',
      'Terms of Service': 'Điều khoản dịch vụ',
      'Contact': 'Liên hệ',
      'Acknowledgements': 'Lời cảm ơn',
      'Notifications': 'Thông báo',
      'Profile': 'Hồ sơ',
      'Movies': 'Phim',
      'Music': 'Âm nhạc',
      'Chat': 'Trò chuyện',
      'Happy': 'Vui vẻ',
      'Sad': 'Buồn',
      'Anxious': 'Lo lắng',
      'Bored': 'Chán',
      'Motivated': 'Có động lực',
      'Romantic': 'Lãng mạn',
    },

    'Indonesian': {
      'History': 'Riwayat',
      'Favourites': 'Favorit',
      'Login': 'Masuk',
      'Logout': 'Keluar',
      'Language': 'Bahasa',
      'Dark Mode': 'Mode gelap',
      'Help & Support': 'Bantuan',
      'About Lix': 'Tentang Lix',
      'Selected': 'Dipilih',
      'No language found': 'Bahasa tidak ditemukan',
      'Search language...': 'Cari bahasa...',
      'Search': 'Cari',
      'Indian': 'India',
      'Foreign': 'Asing',
      'Your Top Moods': 'Suasana hati terbaik Anda',
      'Settings': 'Pengaturan',
      'Contact Us': 'Hubungi kami',
      'FAQs': 'Pertanyaan Umum',
      'Version': 'Versi',
      'Build Number': 'Nomor build',
      'Release Year': 'Tahun rilis',
      'Platform': 'Platform',
      'Data Source': 'Sumber data',
      'Backend': 'Backend',
      'Legal': 'Hukum',
      'Privacy Policy': 'Kebijakan Privasi',
      'Terms of Service': 'Ketentuan Layanan',
      'Contact': 'Kontak',
      'Acknowledgements': 'Ucapan terima kasih',
      'Notifications': 'Notifikasi',
      'Profile': 'Profil',
      'Movies': 'Film',
      'Music': 'Musik',
      'Chat': 'Obrolan',
      'Happy': 'Bahagia',
      'Sad': 'Sedih',
      'Anxious': 'Cemas',
      'Bored': 'Bosan',
      'Motivated': 'Termotivasi',
      'Romantic': 'Romantis',
    },
  };

  // ── Public translate method ───────────────────────────────
  String translate(String key) {
    return _translations[_language]?[key] ??
        _translations['English']?[key] ??
        key;
  }

  // ── Init ──────────────────────────────────────────────────
  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key) ?? 'English';
    _language = saved;
    _locale = _localeMap[saved] ?? const Locale('en');
    notifyListeners();
  }

  // ── Set language ──────────────────────────────────────────
  Future<void> setLanguage(String language) async {
    if (_language == language) return;
    _language = language;
    _locale = _localeMap[language] ?? const Locale('en');
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, language);
    notifyListeners();
  }

  Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_key) ?? 'English';
  }
}
